name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: gustafraga
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2300ff9c&color_dots=%23161b22,%230f2f22,%23145c3f,%231a8c5f,%2300ff9c
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2300ff9c&color_dots=%230d0d0d,%230f2f22,%23145c3f,%231a8c5f,%2300ff9c

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
